name: Blog-Posts
dependencies:
  - python=3.10.6
  - git
  - pip
  - cudatoolkit
  - numba
  - pip:
    - ipykernel==6.27.1
    - jupyterlab==4.0.9
    - shap==0.41.0
    - pandas==1.5.0
    - matplotlib==3.6.0
    - statsmodels==0.13.2
    - seaborn==0.12.0
    - numpy==1.23.0
    - scipy==1.9.1
    - stargazer==0.0.5
    - scikit-learn==1.1.2
    - sympy==1.11.1
    - graphviz==0.20.1
    - econml==0.14.1