name: blog_posts
channels:
  - defaults
  - pip
dependencies:
  - python=3.11.8
  - pip=23.3.1
  - ipykernel=6.28.0
  - jupyterlab=4.0.11
  - shap=0.42.1
  - pandas=2.1.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - numpy=1.26.4
  - scipy=1.11.4
  - scikit-learn=1.2.2
  - sympy=1.12
  - pre-commit=3.4.0
  - python=3.10.6
  - git
  - pip
  - cudatoolkit
  - numba
  - pip:
    - econml==0.15.0
    - stargazer==0.0.6
    - statsmodels==0.14.1
    - ruff==0.3.0
    - graphviz==0.20.1